### ISSUE TITLE
'useFrame' is not exported from 'react-three-fiber'

### ISSUE THREAD

**Issue by nolakat** [drcmda/learnwithjason#7]
I followed the instructions but when I run 'yarn start' it fails to compile and gives me the following error:

./src/App.js
Attempted import error: 'useFrame' is not exported from 'react-three-fiber'.

**Comment by nolakat** [comment]
It looks like updating reac-three-fiber solves the issue, but it is giving me another error that the model is unable to be mapped. Any help is greatly appreciated

**Comment by nestorbonilla** [comment]
Hi @nolakat, same here.
I've tried to reproduce this project, but some components don't work anymore.

Any update on this?

**Comment by DevineJasper** [comment]
The useFrame error can be fixed by updating all packages in the package.json

However, after upgrading, I get errors in the console of the browser, the model doesn't seem to load:

- Uncaught Error: Model suspended while rendering, but no fallback UI was specified.

- The above error occurred in the <Content> component:
    in Content (created by ResizeContainer)
    in div (created by ResizeContainer)
    in ResizeContainer (created by Canvas)
    in Canvas (at App.js:93)
    in App (at src/index.js:6)

Any idea how to fix these?

**Comment by drcmda** [comment]
i have updated it, it was still tied to r3f 2.x

**Comment by prinzuchoudhury** [comment]
I have updated _react-three-fiber_ using _npm update_, but still getting the same error -_'useFrame' is not exported from 'react-three-fiber'_

**Comment by drcmda** [comment]
package json lists r3f 4.x.x now, i think you need to git pull the latest update before you can run npm. it should just be that & npm install.
